>compound Guanosine 5'-diphosphate-D-mannose_Guanosine 5'-diphosphate-D-mannose
#instrument UPLC Q-Tof Premier, Waters
>formula C16H25N5O16P2
#smiles OC[C@@H](O1)[C@@H](O)[C@H](O)[C@H](O)[C@H]1OP(O)(=O)OP(O)(=O)OC[C@@H](O2)[C@@H](O)[C@@H](O)[C@@H]2n(c4)c(N=3)c(n4)C(=O)NC(N)3
#RECORD LC-ESI-QTOF_train_data/PR100564.txt;LC-ESI-QTOF_train_data/PR100142.txt
>charge -1
>ionization [M-H]-
>parentmass 604.06935

>collision 5-60
78.9602 865.0
150.0425 351.7
158.9259 654.3
344.042 299.7
424.0085 454.2
442.0185 393.6
604.0693 2059.0

>collision 5-60
444.0331 6.061
606.085 25.74

