>compound Uridine 5'-diphosphate_Uridine 5'-diphosphate
#instrument UPLC Q-Tof Premier, Waters
>formula C9H14N2O12P2
#smiles O=C(C=2)NC(=O)N(C2)[C@H](O1)[C@H](O)[C@H](O)[C@@H](COP(O)(=O)OP(O)(O)=O)1
#RECORD LC-ESI-QTOF_train_data/PR100616.txt
>charge -1
>ionization [M-H]-
>parentmass 402.9944

>collision 5-60
78.9599 131.5
111.0196 56.98
158.9254 113.7
272.9578 20.22
305.0222 18.64
402.9944 115.9

