>compound S-Adenosyl-L-homocysteine_S-Adenosyl-L-homocysteine
#instrument UPLC Q-Tof Premier, Waters
>formula C14H20N6O5S
#smiles OC(=O)[C@@H](N)CCSC[C@@H](O1)[C@@H](O)[C@@H](O)[C@@H]1n(c3)c(n2)c(n3)c(N)nc2
#RECORD LC-ESI-QTOF_train_data/PR100604.txt;LC-ESI-QTOF_train_data/PR100198.txt
>charge -1
>ionization [M-H]-
>parentmass 383.11378

>collision 5-60
134.047 4440.0
383.1138 1211.0

>collision 5-60
88.0226 1401.0
134.0285 1814.0
136.0631 2738.0
250.0764 337.6
385.1294 550.2

