>compound L-Proline_L-Proline
#instrument UPLC Q-Tof Premier, Waters
>formula C5H9NO2
#smiles OC(=O)C([H])(C1)NCC1
#RECORD LC-ESI-QTOF_train_data/PR100172.txt;LC-ESI-QTOF_train_data/PR100173.txt;LC-ESI-QTOF_train_data/PR100585.txt
>charge 1
>ionization [M+H]+
>parentmass 116.07113

>collision 5-60
70.0658 1050.0
116.0711 469.8

>collision 30
68.0523 2.423
70.0686 187.6
116.0711 2.68

>collision 5-60
114.0555 30.05

