>compound Nicotinic acid_Nicotinic acid
#instrument UPLC Q-Tof Premier, Waters
>formula C6H5NO2
#smiles OC(=O)c(c1)cncc1
#RECORD LC-ESI-QTOF_train_data/PR100505.txt;LC-ESI-QTOF_train_data/PR100045.txt;LC-ESI-QTOF_train_data/PR100046.txt
>charge -1
>ionization [M-H]-
>parentmass 122.02423

>collision 5-60
78.0353 127.9
122.0242 48.12

>collision 5-60
123.9752 18.79
124.0398 1225.0

>collision 30
123.9752 18.79
124.0398 1225.0

