>compound 2'-Deoxyuridine-5'-monophosphate_2'-Deoxyuridine-5'-monophosphate
#instrument UPLC Q-Tof Premier, Waters
>formula C9H13N2O8P
#smiles O=C(C=2)NC(=O)N(C2)[C@@H](C1)O[C@H](COP(O)(O)=O)[C@@H](O)1
#RECORD LC-ESI-QTOF_train_data/PR100526.txt
>charge -1
>ionization [M-H]-
>parentmass 307.03315

>collision 5-60
78.9598 1813.0
96.9696 591.4
111.0199 1139.0
176.9954 288.2
195.0059 953.0
307.0331 1022.0

