>compound delta-Aminolevulinic acid_delta-Aminolevulinic acid
#instrument UPLC Q-Tof Premier, Waters
>formula C5H9NO3
#smiles NCC(=O)CCC(O)=O
#RECORD LC-ESI-QTOF_train_data/PR100221.txt;LC-ESI-QTOF_train_data/PR100633.txt
>charge 1
>ionization [M+H]+
>parentmass 132.06604

>collision 5-60
68.0503 72.34
86.06 690.7
114.0548 567.5
115.9657 80.29
132.066 122.5

>collision 5-60
112.039 10.21
130.0504 45.61

