>compound 2'-Deoxyadenosine_2'-Deoxyadenosine
#instrument UPLC Q-Tof Premier, Waters
>formula C10H13N5O3
#smiles OC[C@@H](O1)[C@@H](O)C[C@@H]1n(c3)c(n2)c(n3)c(N)nc2
#RECORD LC-ESI-QTOF_train_data/PR100081.txt;LC-ESI-QTOF_train_data/PR100080.txt
>charge 1
>ionization [M+H]+
>parentmass 252.10963

>collision 30
117.0574 106.7
136.0651 672.4
252.1096 329.0

>collision 5-60
136.0631 622.4
252.1096 1589.0

