>compound DL-threo-beta-Methylaspartic acid_DL-threo-beta-Methylaspartic acid
#instrument UPLC Q-Tof Premier, Waters
>formula C5H9NO4
#smiles OC(=O)C(C)C(N)C(O)=O
#RECORD LC-ESI-QTOF_train_data/PR100549.txt;LC-ESI-QTOF_train_data/PR100133.txt
>charge -1
>ionization [M-H]-
>parentmass 146.04536

>collision 5-60
85.0295 33.25
102.056 90.65
129.0185 13.57
146.0454 110.6

>collision 5-60
102.0549 4.414
148.061 73.02

