>compound 5-Aminoimidazole-4-carboxamide-1-beta-D-ribofuranosyl 5'-monophosphate_5-Aminoimidazole-4-carboxamide-1-beta-D-ribofuranosyl 5'-monophosphate
#instrument UPLC Q-Tof Premier, Waters
>formula C9H15N4O8P
#smiles NC(=O)c(n2)c(N)n(c2)[C@H](O1)[C@H](O)[C@H](O)[C@@H](COP(O)(O)=O)1
#RECORD LC-ESI-QTOF_train_data/PR100736.txt;LC-ESI-QTOF_train_data/PR100309.txt
>charge -1
>ionization [M-H]-
>parentmass 337.05495

>collision 5-60
78.9601 1836.0
96.9702 828.2
125.0471 378.8
337.055 1234.0

>collision 5-60
97.0287 261.6
110.0355 663.6
127.0618 220.6
206.0571 82.46
339.0706 96.67

