>compound 3-(Methylsulfinyl)propylglucosinolate_3-(Methylsulfinyl)propylglucosinolate
#instrument UPLC Q-Tof Premier, Waters
>formula C11H21NO10S3
#smiles OC[C@@H](O1)[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1SC(CCCS(C)=O)=NOS(O)(=O)=O
#RECORD LC-ESI-QTOF_train_data/PR100429.txt
>charge 1
>ionization [M+K]+
>parentmass 461.99644

>collision 5-60
170.0009 11.06
219.9893 19.85
246.0134 13.33
382.0433 76.78
461.9964 18.13

