>compound E-3,4,5'-Trihydroxy-3'-glucopyranosylstilbene_E-3,4,5'-Trihydroxy-3'-glucopyranosylstilbene
#instrument UPLC Q-Tof Premier, Waters
>formula C20H22O9
#smiles OC[C@@H](O1)[C@@H](O)[C@H](O)[C@@H](O)[C@H](Oc(c2)cc(C=Cc(c3)cc(O)c(O)c3)cc(O)2)1
#RECORD LC-ESI-QTOF_train_data/PR100927.txt
>charge -1
>ionization [M-H]-
>parentmass 405.1158

>collision 5-60
159.0434 15.01
201.0559 11.65
241.0499 42.59
242.0522 28.26
243.0645 93.04
405.1158 19.71

